// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { defineConfig } from 'vitest/config';

export default defineConfig(
    {
    "test": {
      "clearMocks": true,
      "coverage": {
"provider": "v8",
"reporter": [
  "cobertura",
  "text",
  "html",
  "clover",
  "json"
],
"lines": 89,
"functions": 90,
"branches": 89,
"statements": 89,
"exclude": [
  "src/utils/test/*"
]
      },
      "exclude": [
"node_modules",
"dist",
"lib",
".idea",
".git",
".cache"
      ],
      "globals": true,
      "silent": true,
      "watch": false
    }
  }
);
