// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
/**
 * Crates a package.json for the given build type
 */
import fs from 'fs';
import path from 'path';
import { program } from 'commander';

program
  .option('--outDir <string>', 'The directory the file will be written to')
  .option(
    '--type <string>',
    'The package.json type, either commonjs or module'
  );
program.parse();

const options = program.opts();

const type = options.type;

fs.writeFileSync(
  path.join(options.outDir, type, 'package.json'),
  JSON.stringify(
    {
      type,
    },
    null,
    2
  )
);